title: IfState
description: Manage host interface settings in a declarative manner
theme: minima
language: en
date_format: '%Y-%m-%d'
markdown: kramdown
kramdown:
  input: GFM
github:
  repository_url: https://github.com/liske/ifstate
header_pages:
  - index.md
  - install.md
  - cli.md
minima:
  skin: solarized-dark
