title: IfState
description: Manage host interface settings in a declarative manner
author: Thomas Liske

theme: minima
language: en
date_format: '%Y-%m-%d'
markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-redirect-from

github_username: liske
github:
  repository_url: https://github.com/liske/ifstate

header_pages:
  - index.md
  - features.md
  - install.md
  - cli.md
  - schema.md
  - source.md

minima:
  skin: solarized-dark
  social_links:
    github: liske
