title: IfState
description: Manage host interface settings in a declarative manner
author: Thomas Liske

theme: minima
language: en
date_format: '%Y-%m-%d'
markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-redirect-from

mastodon:
- username: liske
  instance: ibh.social

exclude:
  - build.sh
  - update-schema.sh
  - dist
  - test
header_pages:
  - index.md
  - features.md
  - install.md
  - cli.md
  - examples.md
  - schema.md
  - source.md

minima:
  skin: solarized-dark
  social_links:
    mastodon:
    - username: liske
      instance: ibh.social
