#!/usr/bin/env python3

from libifstate.util import ipr
from pprint import pprint

pprint(ipr.get_permaddrs())

exit(0)

import socket
import fcntl
import struct
import array

from pprint import pprint

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, 0)
ifname = "los"

SIOCETHTOOL = 0x8946
ETHTOOL_GPERMADDR = 0x00000020 # Get permanent hardware address

blen = 6

data = array.array("B", struct.pack("II", ETHTOOL_GPERMADDR, blen))
data.extend(b'\x00' * blen)

ifr = struct.pack('16sP', ifname.encode("utf-8"), data.buffer_info()[0])

r = fcntl.ioctl(sock.fileno(), SIOCETHTOOL, ifr)

print(":".join(format(x, "02x") for x in data[8:]))

pprint( data[8:] )
